vendor_app/urls.py
from django.urls import path, re_path
from .views import vendor_create, vendor_list, delete_view, address_view

app_name = 'vendor'

urlpatterns = [
    path('', vendor_create, name='vendor'),
    path('list/', vendor_list, name='vendor_list'),
    re_path(r'^address/(?P<id>\d+)/$', address_view, name='vendor_address'),
    re_path(r'^delete/(?P<id>\d+)/$', delete_view, name='delete'),
]

vendorproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vendor_app.urls', namespace='vendor')),
]

vendor_app/models.py
from django.db import models


# Create your models here.
class Vendor(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    contact_no = models.BigIntegerField()

    def __str__(self):
        return self.name


class VendorAddress(models.Model):
    vendor_id = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    vendor_addr = models.TextField(max_length=200)

vendor_app/views.py
from django.shortcuts import render, redirect
from .models import Vendor, VendorAddress
from .form import VendorForm, VendorAddrForm
from django.db import transaction, IntegrityError
from django.forms import modelformset_factory


# Create your views here.
def vendor_create(request):
    form = VendorForm(request.POST or None)
    addrform = VendorAddrForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid() and addrform.is_valid():
            try:
                with transaction.atomic():
                    insured = form.save(commit=False)
                    insured.save()
                    data = addrform.save(commit=False)
                    data.vendor_id = insured
                    data.save()
            except IntegrityError:
                print("Error Encountere d",IntegrityError.__name__)
    form = VendorForm()
    addrform = VendorAddrForm()
    context = {
        'form': form,
        'addrform': addrform
    }
    return render(request, 'vendor.html', context)


def vendor_list(request):
    vendor = Vendor.objects.all()
    vaddr = VendorAddress.objects.all()
    return render(request, 'vendor_list.html', {'vendor': vendor})

def delete_view(request, id):
    vendor = Vendor.objects.get(id=id)
    vendor.delete()
    return redirect('vendor:vendor_list')


def address_view(request):
    vaddr = VendorAddress.objects.get(id=id)
    return render(request, 'vendor_address.html', {'vaddr': vaddr})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block block_title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        {% block style %}
        {% endblock %}
        body {
            background-color: whitesmoke;
        }

    </style>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/vendor.html
{% extends 'base.html' %}
{% block block_title %}Vendor Create{% endblock %}
{% block style %}
    h1 {
            background-color: aqua;
        }
{% endblock %}
{% block content %}
<h1 class="text-center">Vendor Details Here...</h1>
<div class="container">
<div class="col-md-6">
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ addrform.as_p }}
    <input class="btn btn-success" type="submit" href="{% url 'vendor:vendor_list' %}">
</form>
</div>
</div>
{% endblock %}

templates/vendor_address.html
{% extends 'base.html' %}
{% block block_title %}Vendor address{% endblock %}
{% block content %}
    <p>{{ vaddr.vendor_addr }}</p>
{% endblock %}

templates/vendor_list.html
{% extends 'base.html' %}
{% block block_title %}Vendor Details{% endblock %}
{% block content %}
<div class="container">
<h1 class="text-center">Vendor Details</h1>
{% if vendor.exists %}
<table border="2">
<tr>
    <th>Vendor Name</th>
    <th>Vendor Email</th>
    <th>Vendor Contact No.</th>
    <th>Vendor Address</th>
    <th>Vendor Delete</th>
</tr>
<tr>
    {%  for vd in vendor %}
    <td>{{ vd.name }}</td>
    <td>{{ vd.email }}</td>
    <td>{{ vd.contact_no }}</td>
{#    <td><a href="{% url 'vendor:vendor_address'  %}">click here</a></td>#}
    <td><a href="{% url 'vendor:delete' id=vd.id %}">Delete</a></td>
</tr>
{% endfor %}
</table>
{% else %}
<h1>No Vendor Data Available</h1>
{% endif %}
</div>
{% endblock %}